# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(710, 320, 101, 31))
        self.btn_bw.setObjectName("btn_bw")
        self.btn_mirror = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mirror.setGeometry(QtCore.QRect(710, 240, 101, 31))
        self.btn_mirror.setObjectName("btn_mirror")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(710, 280, 101, 31))
        self.btn_sharp.setObjectName("btn_sharp")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(710, 160, 101, 31))
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(710, 200, 101, 31))
        self.btn_right.setObjectName("btn_right")
        self.list_files = QtWidgets.QListWidget(self.centralwidget)
        self.list_files.setGeometry(QtCore.QRect(10, 61, 171, 491))
        self.list_files.setObjectName("list_files")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(10, 22, 171, 31))
        self.btn_dir.setObjectName("btn_dir")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(190, 60, 491, 491))
        self.image.setObjectName("image")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(710, 400, 101, 31))
        self.btn_2.setObjectName("btn_2")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(710, 480, 101, 31))
        self.btn_4.setObjectName("btn_4")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(710, 440, 101, 31))
        self.btn_3.setObjectName("btn_3")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(710, 360, 101, 31))
        self.btn_1.setObjectName("btn_1")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(710, 520, 101, 31))
        self.btn_5.setObjectName("btn_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageEditor"))
        self.btn_bw.setText(_translate("MainWindow", "Ч/Б"))
        self.btn_mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.btn_2.setText(_translate("MainWindow", "PushButton"))
        self.btn_4.setText(_translate("MainWindow", "PushButton"))
        self.btn_3.setText(_translate("MainWindow", "PushButton"))
        self.btn_1.setText(_translate("MainWindow", "PushButton"))
        self.btn_5.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
